# Generated by Django 3.2.4 on 2022-05-05 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia_uuid', models.UUIDField()),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField()),
                ('ver_mas', models.CharField(max_length=64)),
                ('image_url', models.URLField()),
                ('nombre_libro_1', models.CharField(default=0, max_length=64)),
                ('libro_1', models.URLField(default=0)),
                ('nombre_libro_2', models.CharField(default=0, max_length=64)),
                ('libro_2', models.URLField(default=0)),
                ('nombre_libro_3', models.CharField(default=0, max_length=64)),
                ('libro_3', models.URLField(default=0)),
                ('is_private', models.BooleanField(default=True)),
            ],
        ),
    ]
